### ISSUE TITLE
Sugestion: Please Change Lid Recipes to Use Apricorns Instead of Dyes.

### ISSUE THREAD

**Issue by weirdchildren** [Lord-Of-Crumbs/Create-Cobblemon-Industrialized-Fabric-1.20.x#2]
I think that changing the recipes for the lids to use apricorns instead of dyes whenever applicable, would make a lot more sense and would also make automation more streamlined and less of a hassle. Especially since this would make the Create recipe more closely match the crafting table recipe.

**Comment by Lord-Of-Crumbs** [comment]
The decision on how upper tier lids are constructed was a long discussion among the team, but we eventually came to the idea that we are currently doing. Using dye instead of apricorns keeps the resource consistancy found in the crafting recipes; 1 ball per apricorn. 
The decision to use dye is from the fact that apricorns can be smelted into dye, AND can also be dyed themself, making the process of dying lids to differentiate them, the most intuitive option.
